spring:
  datasource:
    url: jdbc:mysql://localhost/healthcare
    username: root
    password: Jubair@1999
    
  jpa:
    hibernate.ddl-auto: update

    database-platform=org:
      hibernate:
        dialect: MySQL5InnoDBDialect
