spring.mvc.pathmatch.matching-strategy: ant_path_matcher
server.port : 1000
spring:
  datasource:
    url: jdbc:mysql://localhost/healthcare
    username: root
    password : Guna@1996

  jpa:
    hibernate.ddl-auto: update
    database-platform=org:
      hibernate:
        dialect: MySQL8InnoDBDialect

