spring.mvc.pathmatch.matching-strategy: ant_path_matcher
spring:
  datasource:
    url: jdbc:mysql://localhost/healthcare
    username: root
    password : Jubair@1999
  main:
     allow-circular-references: true

  jpa:
    hibernate.ddl-auto: update
    database-platform=org:
      hibernate:
        dialect: MySQL8InnoDBDialect

