spring.mvc.pathmatch.matching-strategy: ant_path_matcher
spring:
  datasource:
    url: jdbc:mysql://localhost/care
    username: root
    password: Jubair@1999

  jpa:
    hibernate.ddl-auto: update
    database-platform=org:
      hibernate:
        dialect: MySQL8InnoDBDialect

